# Generated by Django 2.0.2 on 2018-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0002_auto_20180713_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_evento', models.CharField(choices=[('D', 'Desprendimiento'), ('V', 'Vuelco'), ('DR', 'Deslizamiento Rotacional'), ('DT', 'Deslizamiento Traslacinal'), ('EL', 'Extensión Lateral'), ('F', 'Flujo'), ('C', 'Complejos')], default='Desconocido', max_length=2)),
                ('Tipo_material', models.CharField(choices=[('R', 'Roca'), ('D', 'Detritos'), ('S', 'Suelo')], default='Desconocido', max_length=1)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Fuente', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Estado', models.CharField(default='Desconocido', max_length=25)),
                ('Municipio', models.CharField(default='Desconocido', max_length=25)),
                ('Longitud', models.FloatField(default=200)),
                ('Latitud', models.FloatField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=25)),
                ('Municipio', models.CharField(max_length=25)),
                ('Longitud', models.FloatField()),
                ('Latitud', models.FloatField()),
            ],
        ),
    ]
